config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :dogs
  get '/' => 'welcome#index'

  get 'sessions/new'

  post '/sessions' => 'sessions#create'

  delete 'sessions/:id' => 'sessions#destroy'

  get 'users/new'

  post 'users' => 'users#create'

  get '/users/:id' => 'users#show'

  get '/sessions/destroy' => 'sessions#destroy'

  root 'welcome#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params[:dog]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new

  end
  def create
    @user = User.find_by(email: params[:email])
    if @user.email && @user.authenticate(params[:password])
      set_current_user(@user)
      redirect_to root_path
    else
      render '/sessions/new'
    end
  end
  def destroy
    p session
    session.destroy
    redirect_to root_path
  end
    private
  def set_current_user(user)

    session[:user_id] = user.id
    @current_user = user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
      set_current_user(@user)
      redirect_to 'show'
    else
      render 'users_create_path'
    end
  end
  private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
  def set_current_user(user)
    session[:user_id] = user.id
    @current_user = user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def session?
    !session[:user_id].nil?
  end

  def set_session(user)
    session[:user_id] = user.id
  end

  def set_session_n_redirect_home(user)
    session[:user_id] = user.id
    redirect "/"
  end

  def session_logout_and_redirect
    session.destroy
    redirect '/'
  end
  def current_user
    @user || @user = User.find(session[:user_id])
  end

  def set_session(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/_navbar.html.erb
<a href="/">
      B.A.C.E.
    </a>
    <% if session? %>
      <div>
        Welcome <%= current_user.first_name %>!
      </div>
    <% end %>
    <div>
    <% if session[:user_id] == nil %>
     <div>
        <img src="https://cdn1.iconfinder.com/data/icons/social-black-buttons/512/uber-256.png">
     </div>
     <div>
        <a id="navUberSignUpLink" href="https://login.uber.com/oauth/authorize?response_type=code&client_id=9z6pxBTjyMZZHtdIOndfCfN1pnl_v8q7">
        Uber Sign In
      </a>
     </div>
    <%= link_to "Sign In", sessions_new_path %>
    <%= link_to "Sign up", users_new_path %>
    <% else %>
    <%= link_to "Log Out", users_new_path %>
    <%end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BACE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<navbar><%= render partial: '/layouts/navbar' %></navbar>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for :user, url: '/users' do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
  <h1>Register</h1>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
show.html.erb

app/views/welcome/index.html.erb
<h1> Welcome!</h1>